steps:
  # Docker イメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/keiba-ai-bot:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/keiba-ai-bot:latest',
      '.'
    ]

  # Docker イメージをプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/keiba-ai-bot:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/keiba-ai-bot:latest']

  # Cloud Run にデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'keiba-ai-bot',
      '--image', 'gcr.io/$PROJECT_ID/keiba-ai-bot:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-env-vars', 'GCP_PROJECT_ID=$PROJECT_ID',
      '--set-env-vars', 'LINE_CHANNEL_ACCESS_TOKEN=$$LINE_CHANNEL_ACCESS_TOKEN',
      '--set-env-vars', 'LINE_CHANNEL_SECRET=$$LINE_CHANNEL_SECRET',
      '--memory', '2Gi',
      '--cpu', '2',
      '--max-instances', '10',
      '--timeout', '300'
    ]
    secretEnv: ['LINE_CHANNEL_ACCESS_TOKEN', 'LINE_CHANNEL_SECRET']

# Secret Manager からの環境変数
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/LINE_CHANNEL_ACCESS_TOKEN/versions/latest
      env: 'LINE_CHANNEL_ACCESS_TOKEN'
    - versionName: projects/$PROJECT_ID/secrets/LINE_CHANNEL_SECRET/versions/latest
      env: 'LINE_CHANNEL_SECRET'

# ビルド設定
options:
  machineType: 'E2_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'

# タイムアウト設定
timeout: '600s'
